name: Unzip FramePack

# Manually trigger this workflow from the Actions tab  
on:
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # needed so that git push can add new commits
          fetch-depth: 0

      - name: Verify ZIP exists
        run: |
          if [ ! -f FramePack-main.zip ]; then
            echo "ERROR: FramePack-main.zip not found!" >&2
            exit 1
          fi

      - name: Unzip FramePack-main.zip
        run: |
          # -o to overwrite existing files
          unzip -o FramePack-main.zip -d FramePack-main

      - name: Commit and push extracted files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add FramePack-main
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            git commit -m "Unpack FramePack-main.zip"
            git push
          fi
